jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
         allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "${chart-admin-username}"
        name: "Jenkins Admin"
        password: "${chart-admin-password}"
  disableRememberMe: false
  remotingSecurity:
    enabled: true
  mode: NORMAL
  numExecutors: 0
  projectNamingStrategy: "standard"
  markupFormatter: "plainText"
  clouds:
  - kubernetes:
      containerCapStr: "10"
      jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
      jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
      name: "kubernetes"
      namespace: "jenkins"
      podLabels:
      - key: "jenkins/jenkins-jenkins-agent"
        value: "true"
      serverUrl: "https://kubernetes.default"
      templates:  
      - containers:
        - alwaysPullImage: true
          args: "^${computer.jnlpmac} ^${computer.name}"
          envVars:
          - envVar:
              key: "JENKINS_URL"
              value: "http://jenkins.jenkins.svc.cluster.local:8080/"
          image: "localhost:32000/kathir071083/jenkins-k8s-slave:latest"
          name: "jnlp"
          resourceLimitCpu: "512m"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: "512m"
          resourceRequestMemory: "512Mi"
          workingDir: "/home/jenkins"
        id: "ab619bf5edc4716d93778f56354609e3e317f5a913e0682a18d78ad1cdfdd9db"
        label: "jenkins-jenkins-agent"
        name: "default"
        nodeUsageMode: NORMAL
        podRetention: "never"
        serviceAccount: "jenkins"
        slaveConnectTimeout: 100
        slaveConnectTimeoutStr: "100"
        yamlMergeStrategy: "override"
  - kubernetes:
      containerCap: 10
      containerCapStr: "10"
      credentialsId: "KUBECONFIGSECRETFILE"
      jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
      jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
      name: "CMkubernetes"
      namespace: "jenkins"
      podLabels:
      - key: "jenkins/jenkins-jenkins-agent"
        value: "true"
      templates:
      - containers:
        - envVars:
          - envVar:
              key: "JENKINS_URL"
              value: "http://jenkins.jenkins.svc.cluster.local:8080/"
          image: "localhost:32000/kathir071083/jenkins-k8s-slave:latest"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jnlp"
          privileged: true
          resourceLimitCpu: "512m"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: "512m"
          resourceRequestMemory: "512Mi"
          ttyEnabled: true
          workingDir: "/home/jenkins"
        id: "3f042e92-6a3b-43d4-a51e-b60f8f05a7de"
        label: "cm-jenkins-slave"
        name: "cmjenkins-slave"
        podRetention: "onFailure"
        volumes:
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
        yamlMergeStrategy: "override"
  crumbIssuer:
    standard:
         excludeClientIPFromCrumb: true
security:
  apiToken:
    creationOfLegacyTokenEnabled:  false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled:    true
unclassified:
  location:
    adminAddress: 
    url: http://jenkins:8080
